### ISSUE TITLE
The plugin is not able to scan .cml files if they are provided through an url. 

### ISSUE THREAD

**Issue by morpfl** [jqassistant-plugin/jqassistant-context-mapper-plugin#4]
If a context map (.cml) is provided through a jQA-Plugin, it has to be included in the scanning process via the urls section as shown below. 

```yaml
jqassistant:
  plugins:
    - group-id: org.jqassistant.plugin
      artifact-id: jqassistant-context-mapper-plugin
      version: 2.0.0
  scan:
    include:
      urls:
        - jqassistant-plugin:context-map.cml
```

The configuration leads to the following error occuring during the scanning process:

```
Caused by: java.lang.RuntimeException: Cannot create a resource for 'file:/C:/Users/PF8CBF~1/AppData/Local/Temp/jqassistant-2851799196885517408.tmp'; a registered resource factory is needed
    at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getResource (ResourceSetImpl.java:403)
    at org.contextmapper.dsl.standalone.StandaloneContextMapper.loadCML (StandaloneContextMapper.java:51)
    at org.jqassistant.plugin.contextmapper.ContextMapperScannerPlugin.scan (ContextMapperScannerPlugin.java:41)
    at org.jqassistant.plugin.contextmapper.ContextMapperScannerPlugin.scan (ContextMapperScannerPlugin.java:27)
```

The error does not occur, if the .cml file is loaded as a direct file reference.
